### ISSUE TITLE
rename wavejs to livejs?

### ISSUE THREAD

**Issue by ahdinosaur** [wavejs/talk#1]
i reckon `livejs` makes more sense than `wavejs` for the types of modules we want to have here.

@mmckegg, what do you think about a rename?

**Comment by mmckegg** [comment]
:+1: 

Am happy enough with wavejs, but livejs is a little better.

**Comment by ahdinosaur** [comment]
my feeling is that this ecosystem contains modules do live performances, as opposed to wave processing, manipulation, synthesis, etc.

doing the rename.

**Comment by ahdinosaur** [comment]
done. also new placeholder logo. :confetti_ball:
